import { DataSource } from 'typeorm';
import datasource from '../datasource';
import { Spot } from '../modules/spots/spot.entity';

require('dotenv').config();

const seedSpots = [
  // ===== カフェ =====
  {
    name: 'スターバックスコーヒー 丸の内オアゾ店',
    category: 'cafe',
    latitude: 35.6863,
    longitude: 139.7658,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-6-4',
  },
  {
    name: 'ドトールコーヒーショップ 東京駅八重洲口店',
    category: 'cafe',
    latitude: 35.6804,
    longitude: 139.7701,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1',
  },
  {
    name: 'タリーズコーヒー 新丸の内ビル店',
    category: 'cafe',
    latitude: 35.6857,
    longitude: 139.7647,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-5-1',
  },
  {
    name: 'ブルーボトルコーヒー 丸の内カフェ',
    category: 'cafe',
    latitude: 35.6812,
    longitude: 139.7637,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内2-4-1',
  },
  {
    name: 'エクセルシオールカフェ 東京駅前店',
    category: 'cafe',
    latitude: 35.6814,
    longitude: 139.7679,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1',
  },
  {
    name: 'コメダ珈琲店 大手町店',
    category: 'cafe',
    latitude: 35.6866,
    longitude: 139.7629,
    description: '',
    image_url: '',
    address: '東京都千代田区大手町1-2-1',
  },
  {
    name: 'ルノアール 丸の内店',
    category: 'cafe',
    latitude: 35.6844,
    longitude: 139.7663,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内3-2-1',
  },
  {
    name: 'プロント 有楽町店',
    category: 'cafe',
    latitude: 35.6756,
    longitude: 139.7625,
    description: '',
    image_url: '',
    address: '東京都千代田区有楽町2-9-18',
  },
  {
    name: 'カフェ・ベローチェ 銀座一丁目店',
    category: 'cafe',
    latitude: 35.6742,
    longitude: 139.7668,
    description: '',
    image_url: '',
    address: '東京都中央区銀座1-13-4',
  },
  {
    name: 'サードウェーブコーヒー 丸の内',
    category: 'cafe',
    latitude: 35.6825,
    longitude: 139.7641,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内2-1-1',
  },

  // ===== レストラン =====
  {
    name: '丸の内タニタ食堂',
    category: 'restaurant',
    latitude: 35.6848,
    longitude: 139.7648,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内2-7-2',
  },
  {
    name: '天丼てんや 東京八重洲口店',
    category: 'restaurant',
    latitude: 35.6812,
    longitude: 139.7712,
    description: '',
    image_url: '',
    address: '東京都中央区八重洲2-1-1',
  },
  {
    name: '大戸屋ごはん処 東京駅店',
    category: 'restaurant',
    latitude: 35.6808,
    longitude: 139.7695,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1',
  },
  {
    name: '吉野家 東京駅八重洲口店',
    category: 'restaurant',
    latitude: 35.6811,
    longitude: 139.7709,
    description: '',
    image_url: '',
    address: '東京都中央区八重洲2-1',
  },
  {
    name: '牛たん炭焼き利久 東京駅店',
    category: 'restaurant',
    latitude: 35.6818,
    longitude: 139.7697,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1 グランスタ東京',
  },
  {
    name: '銀座ライオン 丸の内店',
    category: 'restaurant',
    latitude: 35.6845,
    longitude: 139.7651,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内3-4-1',
  },
  {
    name: 'ラーメン凪 東京駅店',
    category: 'restaurant',
    latitude: 35.6813,
    longitude: 139.7688,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1',
  },
  {
    name: '松屋 丸の内店',
    category: 'restaurant',
    latitude: 35.6832,
    longitude: 139.7641,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内2-4-1',
  },
  {
    name: '丸の内ハウス',
    category: 'restaurant',
    latitude: 35.6858,
    longitude: 139.7648,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-5-1 新丸ビル7F',
  },
  {
    name: '寿司の美登利 東京駅店',
    category: 'restaurant',
    latitude: 35.6816,
    longitude: 139.7701,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1 グランスタ東京',
  },

  // ===== 公園 =====
  {
    name: '皇居外苑',
    category: 'park',
    latitude: 35.6836,
    longitude: 139.7536,
    description: '',
    image_url: '',
    address: '東京都千代田区皇居外苑1-1',
  },
  {
    name: '和田倉噴水公園',
    category: 'park',
    latitude: 35.6835,
    longitude: 139.7585,
    description: '',
    image_url: '',
    address: '東京都千代田区皇居外苑',
  },
  {
    name: '日比谷公園',
    category: 'park',
    latitude: 35.6737,
    longitude: 139.7572,
    description: '',
    image_url: '',
    address: '東京都千代田区日比谷公園1-6',
  },
  {
    name: '大手町の森',
    category: 'park',
    latitude: 35.6871,
    longitude: 139.7625,
    description: '',
    image_url: '',
    address: '東京都千代田区大手町1-3-3',
  },
  {
    name: '北の丸公園',
    category: 'park',
    latitude: 35.6951,
    longitude: 139.754,
    description: '',
    image_url: '',
    address: '東京都千代田区北の丸公園1-1',
  },
  {
    name: '東京駅前広場',
    category: 'park',
    latitude: 35.6805,
    longitude: 139.767,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9',
  },
  {
    name: '行幸通り緑道',
    category: 'park',
    latitude: 35.6827,
    longitude: 139.7611,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内',
  },
  {
    name: '有楽町公園',
    category: 'park',
    latitude: 35.6739,
    longitude: 139.7625,
    description: '',
    image_url: '',
    address: '東京都千代田区有楽町1-1',
  },
  {
    name: '汐留公園',
    category: 'park',
    latitude: 35.6634,
    longitude: 139.7588,
    description: '',
    image_url: '',
    address: '東京都港区東新橋1-6',
  },
  {
    name: '浜離宮恩賜庭園',
    category: 'park',
    latitude: 35.6564,
    longitude: 139.7622,
    description: '',
    image_url: '',
    address: '東京都中央区浜離宮庭園1-1',
  },

  // ===== ショッピング =====
  {
    name: '丸の内ビルディング（丸ビル）',
    category: 'shopping',
    latitude: 35.6823,
    longitude: 139.7653,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内2-4-1',
  },
  {
    name: '新丸の内ビルディング（新丸ビル）',
    category: 'shopping',
    latitude: 35.6826,
    longitude: 139.7646,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-5-1',
  },
  {
    name: 'KITTE 丸の内',
    category: 'shopping',
    latitude: 35.6798,
    longitude: 139.7664,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内2-7-2',
  },
  {
    name: '大丸東京店',
    category: 'shopping',
    latitude: 35.6802,
    longitude: 139.7706,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1',
  },
  {
    name: '有楽町マルイ',
    category: 'shopping',
    latitude: 35.6755,
    longitude: 139.7629,
    description: '',
    image_url: '',
    address: '東京都千代田区有楽町2-7-1',
  },
  {
    name: '銀座三越',
    category: 'shopping',
    latitude: 35.6715,
    longitude: 139.7664,
    description: '',
    image_url: '',
    address: '東京都中央区銀座4-6-16',
  },
  {
    name: '三越日本橋本店',
    category: 'shopping',
    latitude: 35.6842,
    longitude: 139.7746,
    description: '',
    image_url: '',
    address: '東京都中央区日本橋室町1-4-1',
  },
  {
    name: 'イトシア有楽町',
    category: 'shopping',
    latitude: 35.6748,
    longitude: 139.7626,
    description: '',
    image_url: '',
    address: '東京都千代田区有楽町2-7-1',
  },
  {
    name: 'アトレ有楽町',
    category: 'shopping',
    latitude: 35.675,
    longitude: 139.7626,
    description: '',
    image_url: '',
    address: '東京都千代田区有楽町2-7-1',
  },
  {
    name: 'エキュート東京',
    category: 'shopping',
    latitude: 35.6807,
    longitude: 139.7673,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1 東京駅構内',
  },

  // ===== 観光 =====
  {
    name: '東京駅（赤レンガ駅舎）',
    category: 'tourism',
    latitude: 35.6812,
    longitude: 139.7671,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1',
  },
  {
    name: '皇居東御苑',
    category: 'tourism',
    latitude: 35.6876,
    longitude: 139.7574,
    description: '',
    image_url: '',
    address: '東京都千代田区千代田1',
  },
  {
    name: '二重橋',
    category: 'tourism',
    latitude: 35.6806,
    longitude: 139.754,
    description: '',
    image_url: '',
    address: '東京都千代田区皇居外苑',
  },
  {
    name: '大手門',
    category: 'tourism',
    latitude: 35.6879,
    longitude: 139.7586,
    description: '',
    image_url: '',
    address: '東京都千代田区千代田1',
  },
  {
    name: '靖国神社',
    category: 'tourism',
    latitude: 35.694,
    longitude: 139.7444,
    description: '',
    image_url: '',
    address: '東京都千代田区九段北3-1-1',
  },
  {
    name: '東京国際フォーラム',
    category: 'tourism',
    latitude: 35.6763,
    longitude: 139.7634,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内3-5-1',
  },
  {
    name: '銀座四丁目交差点',
    category: 'tourism',
    latitude: 35.6718,
    longitude: 139.7657,
    description: '',
    image_url: '',
    address: '東京都中央区銀座4丁目',
  },
  {
    name: '歌舞伎座',
    category: 'tourism',
    latitude: 35.6696,
    longitude: 139.7667,
    description: '',
    image_url: '',
    address: '東京都中央区銀座4-12-15',
  },
  {
    name: '築地市場跡地',
    category: 'tourism',
    latitude: 35.6634,
    longitude: 139.7696,
    description: '',
    image_url: '',
    address: '東京都中央区築地5-2-1',
  },
  {
    name: '日本橋',
    category: 'tourism',
    latitude: 35.6832,
    longitude: 139.7742,
    description: '',
    image_url: '',
    address: '東京都中央区日本橋1丁目',
  },

  // ===== コンビニ =====
  {
    name: 'セブン-イレブン 東京丸の内1丁目店',
    category: 'convenience',
    latitude: 35.6854,
    longitude: 139.7644,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-2-1',
  },
  {
    name: 'ファミリーマート 東京駅前店',
    category: 'convenience',
    latitude: 35.6809,
    longitude: 139.7673,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1',
  },
  {
    name: 'ローソン 東京八重洲通り店',
    category: 'convenience',
    latitude: 35.6814,
    longitude: 139.7706,
    description: '',
    image_url: '',
    address: '東京都中央区八重洲2-4-1',
  },
  {
    name: 'セブン-イレブン 大手町駅前店',
    category: 'convenience',
    latitude: 35.6869,
    longitude: 139.7624,
    description: '',
    image_url: '',
    address: '東京都千代田区大手町1-6-1',
  },
  {
    name: 'ファミリーマート 有楽町駅前店',
    category: 'convenience',
    latitude: 35.6752,
    longitude: 139.7628,
    description: '',
    image_url: '',
    address: '東京都千代田区有楽町2-10-1',
  },
  {
    name: 'ローソン 銀座一丁目店',
    category: 'convenience',
    latitude: 35.6736,
    longitude: 139.7673,
    description: '',
    image_url: '',
    address: '東京都中央区銀座1-14-1',
  },
  {
    name: 'セブン-イレブン 丸の内二丁目店',
    category: 'convenience',
    latitude: 35.6836,
    longitude: 139.7648,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内2-2-1',
  },
  {
    name: 'ミニストップ 日本橋店',
    category: 'convenience',
    latitude: 35.6844,
    longitude: 139.7748,
    description: '',
    image_url: '',
    address: '東京都中央区日本橋2-3-1',
  },
  {
    name: 'ファミリーマート 日比谷公園前店',
    category: 'convenience',
    latitude: 35.6744,
    longitude: 139.7579,
    description: '',
    image_url: '',
    address: '東京都千代田区日比谷公園1',
  },
  {
    name: 'セブン-イレブン 銀座コリドー店',
    category: 'convenience',
    latitude: 35.6722,
    longitude: 139.7633,
    description: '',
    image_url: '',
    address: '東京都中央区銀座3-9-3',
  },

  // ===== 病院 =====
  {
    name: '聖路加国際病院',
    category: 'hospital',
    latitude: 35.6659,
    longitude: 139.7727,
    description: '',
    image_url: '',
    address: '東京都中央区明石町9-1',
  },
  {
    name: '東京逓信病院',
    category: 'hospital',
    latitude: 35.6953,
    longitude: 139.7434,
    description: '',
    image_url: '',
    address: '東京都千代田区富士見2-14-23',
  },
  {
    name: '順天堂大学医学部附属順天堂医院',
    category: 'hospital',
    latitude: 35.7062,
    longitude: 139.7617,
    description: '',
    image_url: '',
    address: '東京都文京区本郷3-1-3',
  },
  {
    name: '丸の内クリニック',
    category: 'hospital',
    latitude: 35.6822,
    longitude: 139.7648,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内3-4-1',
  },
  {
    name: '東京駅医務室',
    category: 'hospital',
    latitude: 35.6816,
    longitude: 139.7671,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1 東京駅構内',
  },
  {
    name: '千代田区立九段診療所',
    category: 'hospital',
    latitude: 35.693,
    longitude: 139.7519,
    description: '',
    image_url: '',
    address: '東京都千代田区九段南1-6-17',
  },
  {
    name: '日本橋診療所',
    category: 'hospital',
    latitude: 35.6844,
    longitude: 139.7753,
    description: '',
    image_url: '',
    address: '東京都中央区日本橋2-5-1',
  },
  {
    name: '有楽町クリニック',
    category: 'hospital',
    latitude: 35.6753,
    longitude: 139.7628,
    description: '',
    image_url: '',
    address: '東京都千代田区有楽町1-1-2',
  },
  {
    name: '銀座クリニック',
    category: 'hospital',
    latitude: 35.6712,
    longitude: 139.7658,
    description: '',
    image_url: '',
    address: '東京都中央区銀座5-1-1',
  },
  {
    name: '京橋医療センター',
    category: 'hospital',
    latitude: 35.6763,
    longitude: 139.7714,
    description: '',
    image_url: '',
    address: '東京都中央区京橋2-4-12',
  },

  // ===== 駅 =====
  {
    name: '東京駅',
    category: 'station',
    latitude: 35.6812,
    longitude: 139.7671,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内1-9-1',
  },
  {
    name: '有楽町駅',
    category: 'station',
    latitude: 35.6751,
    longitude: 139.7632,
    description: '',
    image_url: '',
    address: '東京都千代田区有楽町2-9-1',
  },
  {
    name: '二重橋前駅',
    category: 'station',
    latitude: 35.6803,
    longitude: 139.761,
    description: '',
    image_url: '',
    address: '東京都千代田区丸の内3-1',
  },
  {
    name: '大手町駅',
    category: 'station',
    latitude: 35.6862,
    longitude: 139.7629,
    description: '',
    image_url: '',
    address: '東京都千代田区大手町1',
  },
  {
    name: '日本橋駅',
    category: 'station',
    latitude: 35.6827,
    longitude: 139.7745,
    description: '',
    image_url: '',
    address: '東京都中央区日本橋室町1',
  },
  {
    name: '京橋駅',
    category: 'station',
    latitude: 35.6763,
    longitude: 139.772,
    description: '',
    image_url: '',
    address: '東京都中央区京橋2',
  },
  {
    name: '銀座駅',
    category: 'station',
    latitude: 35.6717,
    longitude: 139.7657,
    description: '',
    image_url: '',
    address: '東京都中央区銀座4',
  },
  {
    name: '日比谷駅',
    category: 'station',
    latitude: 35.6731,
    longitude: 139.7589,
    description: '',
    image_url: '',
    address: '東京都千代田区内幸町1',
  },
  {
    name: '新橋駅',
    category: 'station',
    latitude: 35.666,
    longitude: 139.7588,
    description: '',
    image_url: '',
    address: '東京都港区新橋2-17-1',
  },
  {
    name: '茅場町駅',
    category: 'station',
    latitude: 35.679,
    longitude: 139.781,
    description: '',
    image_url: '',
    address: '東京都中央区日本橋茅場町1',
  },
];

export async function runSeed(ds: DataSource) {
  const spotRepository = ds.getRepository(Spot);

  const count = await spotRepository.count();
  if (count > 0) {
    console.log(`シードデータは既に存在します（${count}件）。スキップします。`);
    return;
  }

  await spotRepository.save(seedSpots);
  console.log(`✓ シードデータを投入しました（${seedSpots.length}件）`);
}

async function seed() {
  await datasource.initialize();
  await runSeed(datasource);
  await datasource.destroy();
}

if (require.main === module) {
  seed().catch((error) => {
    console.error('シードエラー:', error);
    process.exit(1);
  });
}
